source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OSSystems_Example', :exclusive => true do
  pod 'OSSystems', :path => '../'
end

target 'OSSystems_Tests', :exclusive => true do
  pod 'OSSystems', :path => '../'

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
